--DROP TABLE CUSTOMER_INFO;
--DROP SEQUENCE CUSTOMER_INFO_SEQ;


CREATE TABLE CUSTOMER_INFO(CUSTOMER_ID int NOT NULL PRIMARY KEY,FIRST_NAME varchar(50),LAST_NAME varchar(50),ADDRESS varchar(1000),STATE varchar(50),COUNTRY varchar(50),EMAIL_ID varchar(100), PAN varchar(50) ,CONTACT_NO varchar(50), DOB DATE
);

CREATE SEQUENCE CUSTOMER_INFO_SEQ Start with 1 increment by 1;

