DROP TABLE DUE_DILIGENCE_STATUS;
DROP SEQUENCE DUE_DILIGENCE_STATUS_SEQ;


CREATE TABLE DUE_DILIGENCE_STATUS(ID INT NOT NULL PRIMARY KEY,CUSTOMER_ID INT NOT NULL ,DUE_DILIGENCE_STATUS varchar(50),APPROVAL_STATUS varchar(50));

CREATE SEQUENCE DUE_DILIGENCE_STATUS_SEQ Start with 1 increment by 1;


DELETE FROM DUE_DILIGENCE_STATUS;

INSERT INTO DUE_DILIGENCE_STATUS (ID,CUSTOMER_ID,DUE_DILIGENCE_STATUS,APPROVAL_STATUS) VALUES
(1,1,'STANDARD','APPROVED'));

--INSERT INTO EMPLOYEE (EMP_ID,FIRST_NAME,LAST_NAME,DOJ) VALUES
--(2,'JOHN','G',current_date());